development: &default
  adapter: postgresql
  database: wolfgang_wallace_development
  min_messages: WARNING
  pool: 5
  username: postgres
  host: db

test:
  <<: *default
  database: wolfgang_wallace_test

production:
  <<: *default
  database: wolfgang_wallace_production
  username: wolfgang_wallace
  password: <%= ENV['WOLFGANG_WALLACE_DATABASE_PASSWORD'] %>
