social_media:
  facebook:
    url: https://www.facebook.com/wolfgangwallaceband
  instagram:
    url: https://www.instagram.com/wolfgangwallaceband
  soundcloud:
    url: https://soundcloud.com/wolfgangwallaceband

contact_methods:
  email: contact@wolfgangwallace.com

soundcloud:
  tracks:
    - 526502217
    - 538415868
    - 585403437

facebook:
  videos:
    - orientation: landscape
      id: 284874722188255
    - orientation: portrait
      id: 360399978116114
    - orientation: landscape
      id: 2217396525142296

schedule:
  shows:
    - venue:
        name: Radio Room
        address: 110 Poinsett Hwy, Greenville, SC 29609
        address_url: https://www.google.com/maps/place/110+Poinsett+Hwy,+Greenville,+SC+29609
        url: http://www.radioroomgreenville.com/calendar/2019/4/8/the-happy-fits-and-deal-casino
      date: 2019-04-08
    - venue:
        name: Radio Room
        address: 110 Poinsett Hwy, Greenville, SC 29609
        address_url: https://www.google.com/maps/place/110+Poinsett+Hwy,+Greenville,+SC+29609
        url: http://www.radioroomgreenville.com/calendar/2019/5/3/sexbruise
      date: 2019-05-03
