social_media:
  facebook:
    url: https://www.facebook.com/wolfgangwallaceband
  instagram:
    url: https://www.instagram.com/wolfgangwallaceband
  soundcloud:
    url: https://soundcloud.com/wolfgangwallaceband

contact_methods:
  email: contact@wolfgangwallace.com

